version: "2"

services:
  # php-fpm:
  #   build: ./php-fpm
  #   volumes:
  #     - ../:/var/www
  #   expose:
  #     - "9000"
  #   environment:
  #     MYSQL_HOST: mysql
  #     MYSQL_USERNAME: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #     DB_NAME: ${MYSQL_DATABASE}
  #     MYSQL_PORT: 3306

  apache:
    image: webdevops/php-apache:8.2
    volumes:
      # - ./logs/apache:/var/log/apache2
      # - ./apache/sites:/etc/apache2/sites-available
      - ../:/app/
    env_file: .env
    environment:
      MYSQL_HOST: mysql
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      MYSQL_PORT: 3306
    ports:
      - "80:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
