FROM nginx:latest

ARG PHP_SOCKET=php-fpm:9000

ENV WEB_PHP_SOCKET=$PHP_SOCKET

# ENV WEB_DOCUMENT_ROOT=/var/www/

EXPOSE 80 443

# WORKDIR /var/www/

# COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

# ENTRYPOINT ["/opt/docker/bin/entrypoint.sh"]

# CMD ["supervisord"]
