version: "2"

services:
  php-fpm:
    build: ./php-fpm
    platform: linux/amd64
    volumes:
      - ./www:/usr/share/nginx/html
    expose:
      - "9000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      MYSQL_PORT: 3306

  nginx:
    build: ./nginx
    platform: linux/amd64
    ports:
      - "80:80"
      - "443:8443"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      # - ./www:/usr/share/nginx/html
      - ./www:/var/www
      - ./logs:/var/log/nginx
    depends_on:
      - php-fpm

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
